# Generated by Django 4.0.1 on 2022-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
