# Generated by Django 4.0.1 on 2022-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_post_alter_topic_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='message',
        ),
    ]
