# Generated by Django 4.0.1 on 2022-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_topic_message_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
