# Generated by Django 4.0.1 on 2022-01-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_topic_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='file',
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
