# Generated by Django 4.0.1 on 2022-01-28 13:50

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_remove_topic_file_alter_topic_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
