# Generated by Django 4.0.1 on 2022-01-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_alter_topic_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file_path',
            field=models.TextField(null=True),
        ),
    ]
