# Generated by Django 4.0.1 on 2022-01-29 12:38

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_alter_topic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(null=True, upload_to=boards.models.user_directory_path),
        ),
    ]
